# @package _global_

defaults:
  - /benchmark/nav/pointnav: pointnav_hm3d
  - /habitat_baselines: habitat_baselines_rl_config_base
  - _self_

habitat:
  task:
    success_reward: 0.0
    slack_reward: 0.0

habitat_baselines:
  verbose: False
  trainer_name: "ddppo"
  torch_gpu_id: 0
  tensorboard_dir: "data/hm3d/debug/tb"
  video_dir: "data/hm3d/debug/videos"
  test_episode_count: -1
  eval_ckpt_path_dir: "data/hm3d/debug/new_checkpoints"
  num_environments: 4
  checkpoint_folder: "data/hm3d/debug/new_checkpoints"
  num_updates: -1
  total_num_steps: 2e7
  log_interval: 1
  log_file: "data/hm3d/debug/train.log"
  num_checkpoints: 100
  # Force PyTorch to be single threaded as
  # this improves performance considerably
  force_torch_single_threaded: True
  load_resume_state_config: False

  # Costom configs
  reward_free: True

  rl:
    policy:
      main_agent:
        name: "PointNavResNetPolicy"

    ppo:
      # ppo params
      clip_param: 0.2
      ppo_epoch: 2
      num_mini_batch: 2
      value_loss_coef: 0.5
      entropy_coef: 0.01
      lr: 2.5e-4
      eps: 1e-5
      max_grad_norm: 0.2
      num_steps: 128
      use_gae: True
      gamma: 0.99
      tau: 0.95
      use_linear_clip_decay: False
      use_linear_lr_decay: False
      reward_window_size: 50

      use_normalized_advantage: False

      hidden_size: 512

      # Use double buffered sampling, typically helps
      # when environment time is similar or larger than
      # policy inference time during rollout generation
      use_double_buffered_sampler: False

    ddppo:
      sync_frac: 0.6
      # The PyTorch distributed backend to use
      distrib_backend: NCCL
      # Visual encoder backbone
      pretrained_weights: data/ddppo-models/gibson-2plus-resnet50.pth
      # Initialize with pretrained weights
      pretrained: False
      # Initialize just the visual encoder backbone with pretrained weights
      pretrained_encoder: False
      # Whether the visual encoder backbone will be trained.
      train_encoder: True
      # Whether to reset the critic linear layer
      reset_critic: True

      # Model parameters
      backbone: resnet50
      rnn_type: LSTM
      num_recurrent_layers: 2

    explore:
      int_rew_coef: 0.1
      model_learning_rate: 2.5e-4
      model_n_epochs: 3

      icm:
        forward_loss_coef: 0.2

      e3b:
        ridge: 0.1
